## 웹 페이지 자동 수집

### 셀레니움

- 웹 브라우저를 자동으로 제어하는 파이썬 라이브러리(패키지)
- 기능
    - 브라우저 실행
    - 웹 페이지 로드(접속)
    - 입력창에 글자 입력(아이디, 패스워드 등)
    - 버튼 클릭
    - 페이지 이동
    - 화면에 표시된 텍스트 추출
    - 특정 이미지 저장 / 화면 스크린 캡처
    - 반복 자동화

- 정적인 HTML 은 Beautifulsoup4, request 패키지로 수집가능
- 동적인 웹화면은 selenium이 강력함. 정적인 웹페이지도 가능

#### 웹브라우저 실행

In [68]:
# 셀레니움 패키지 로드
from selenium import webdriver
import pandas as pd

In [ ]:
# 웹브라우저 프로세스를 파이썬이 driver 변수로 관리
driver = webdriver.Chrome()

driver.get(f'http://www.naver.com')

In [ ]:
#웹브라우저 종료
driver.quit()

#### 웹페이지 스크래핑 실습

In [ ]:
driver = webdriver.Chrome()
driver.get(f'http://127.0.0.1:5500/ch04/products.html')

##### 요소찾기

- 주요 요소 찾기 방식
    - `By.ID` : ID로 찾기
    - `By.CLASS_NSME` : class명으로 찾기
    - `By.CSS_SELECTOR` : CSS 선택자 방법으로 찾기
    - `By.XPATH` : XPath로 찾기

In [ ]:
# css 선택자로 요소찾는 함수용 패키지 안에 있는 클래스를 로드
from selenium.webdriver.common.by import By

In [ ]:
# 페이지 내 하나의 데이터만 추출
title = driver.find_element(By.ID, 'title')

title.text

'상품목록'

In [ ]:
# 페이지 내 여러 요소를 동시에 추출

products = driver.find_elements(By.CLASS_NAME, 'product')

len(products)

for product in products:
    print(product.text)

키보드 30000
마우스 15000
모니터 250000

##### css 선택자로 요소 추출

In [ ]:
products = driver.find_elements(By.CSS_SELECTOR, '.product')


for product in products:
    print(product)
    name = product.find_element(By.CSS_SELECTOR, '.name').text
    print(name)

<selenium.webdriver.remote.webelement.WebElement (session="d83f5bc2d2a6923f513b1404a14827f2", element="f.69E1764DB2CF0194948C3723EA68EA0D.d.664871651503EE563411128A9264DF7A.e.16")>
키보드
<selenium.webdriver.remote.webelement.WebElement (session="d83f5bc2d2a6923f513b1404a14827f2", element="f.69E1764DB2CF0194948C3723EA68EA0D.d.664871651503EE563411128A9264DF7A.e.17")>
마우스
<selenium.webdriver.remote.webelement.WebElement (session="d83f5bc2d2a6923f513b1404a14827f2", element="f.69E1764DB2CF0194948C3723EA68EA0D.d.664871651503EE563411128A9264DF7A.e.18")>
모니터

##### 입력창 입력

In [ ]:
keyword_input = driver.find_element(By.ID, 'keyword')
keyword_input.send_keys('USB');

In [ ]:
keyword_input.clear()

In [ ]:
keyword_input.send_keys('테슬라')

StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=153.0.8010.54); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff7e8f11035+5a95]
	chromedriver!(No symbol) [0x7ff7e8e32c70]
	chromedriver!(No symbol) [0x7ff7e8c54a7d]
	chromedriver!(No symbol) [0x7ff7e8c6c34d]
	chromedriver!(No symbol) [0x7ff7e8c6adb0]
	chromedriver!(No symbol) [0x7ff7e8c5d7d5]
	chromedriver!(No symbol) [0x7ff7e8c5b5be]
	chromedriver!(No symbol) [0x7ff7e8c5faa5]
	chromedriver!(No symbol) [0x7ff7e8c5fb6f]
	chromedriver!(No symbol) [0x7ff7e8cb119e]
	chromedriver!(No symbol) [0x7ff7e8cb1293]
	chromedriver!(No symbol) [0x7ff7e8ca75cd]
	chromedriver!(No symbol) [0x7ff7e8cd93ea]
	chromedriver!(No symbol) [0x7ff7e8ca3396]
	chromedriver!(No symbol) [0x7ff7e8cffbea]
	chromedriver!(No symbol) [0x7ff7e8ca1d02]
	chromedriver!(No symbol) [0x7ff7e8ca2b13]
	chromedriver!GetHandleVerifier [0x7ff7e9331411+425e71]
	chromedriver!GetHandleVerifier [0x7ff7e935ca47+4514a7]
	chromedriver!GetHandleVerifier [0x7ff7e935094e+4453ae]
	chromedriver!GetHandleVerifier [0x7ff7e900bf6e+1009ce]
	chromedriver!(No symbol) [0x7ff7e8e40a05]
	chromedriver!(No symbol) [0x7ff7e8e3bcf4]
	chromedriver!(No symbol) [0x7ff7e8e3be84]
	chromedriver!(No symbol) [0x7ff7e8e266ac]
	KERNEL32!BaseThreadInitThunk [0x7ffe0d8dcd87+17]
	ntdll!RtlUserThreadStart [0x7ffe0e30caec+2c]

In [ ]:
# 입력태그에서 텍스트 가져오기
keyword_str = driver.find_element(By.ID, 'keyword')

keyword_str.get_attribute('value')

'USB'

##### 버튼 클릭

In [5]:
button = driver.find_element(By.ID, 'search-btn')
button.click()

NameError: name 'driver' is not defined

#### 명시적 대기

- 링크 클릭으로 다른 페이지 이동, 검색 후 결과 대기까지 시간이 소요
- `time.sleep(2)` 2초동안 대기 등의 파이썬 기본 함수가 제약사항이 많음
- 특정 조건이 만족할때까지 대기하는 로직 사용

In [4]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [3]:
# 여러 작업 수행 후

wait = WebDriverWait(driver, 10) # 10초 대기

title = wait.until(
    EC.presence_of_element_located((By.ID, 'title'))

)
title.text

NameError: name 'driver' is not defined

##### 데이터 수집하기

In [ ]:
products = driver.find_elements(By.CLASS_NAME, 'product')

result = []

for product in products:
    name = product.find_element(By.CSS_SELECTOR, '.name').text
    price = product.find_element(By.CLASS_NAME, 'price').text

    result.append({'name': name, 'price': price})

#### 정리
- 웹 스크래핑시 필요요소
    - 웹드라이버로 웹사이트 오픈
    - 필요 요소 찾기
    - 입력태그 찾기
    - 버튼 요소 찾기
    - 입력하고 버튼 클릭해서 동작
    - 데이터 가져오기
    - 화면이 갱신되기까지 명시적 대기

result

In [ ]:
result

[{'name': '키보드', 'price': '30000'},
 {'name': '마우스', 'price': '15000'},
 {'name': '모니터', 'price': '250000'}]

In [ ]:
df = pd.DataFrame(result)
df

  name   price
0  키보드   30000
1  마우스   15000
2  모니터  250000

In [ ]:
df.to_csv('../data/scrap_products.csv', encoding='utf-8')

#### 실습
##### 멜론 사이트 TOP100 스크래핑

In [1]:
# 패키지로드
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [2]:
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)
driver.get('https://www.melon.com/chart/index.htm')

company_name = wait.until(
    EC.presence_of_element_located((By.ID, 'footer'))
)

#### 차트의 곡 행 가져오기ㅏ

In [5]:
# css 선택자 입력시 태그 + .css

songs = driver.find_elements(By.CSS_SELECTOR, '.lst50, .lst100')

datas = []


# len(songs)
for song in songs:
    # 노래 순위
    rank = song.find_element(By.CSS_SELECTOR, '.rank').text
    #노래 제목
    title = song.find_element(By.CSS_SELECTOR, '.rank01 > span > a').text
    #가수명
    singer = song.find_element(By.CSS_SELECTOR, '.rank02 a').text
    # print(singer)
    # print(rank, title)
    # 앨범명
    albumn =song.find_element(By.CSS_SELECTOR, '.rank03 a').text

    # 좋아요 개수
    like = song.find_element(By.CLASS_NAME, 'cnt').text

    # 단계 상승하락
    rank_ud = song.find_element(By.CSS_SELECTOR, '.rank_wrap').get_attribute('title')
    

    # print(rank, title, singer, albumn,  like)

    datas.append({
        '순위': rank,
        '순위변동': rank_ud,  
        '노래순위': title,
        '가수': singer,
        '앨범': albumn,
        '좋아요': like
    })

In [ ]:
driver.quit()

In [6]:
df_melon100 = pd.DataFrame(datas)
df_melon100

,순위,순위변동,노래순위,가수,앨범,좋아요
0,1,순위 동일,퇴사할게여 (Narr. 기안84),소연 (SOYEON),끝내주는 인생,"39,517"
1,2,순위 동일,LOVE ATTACK,RESCENE (리센느),SCENEDROME,"153,142"
2,3,순위 동일,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],"80,177"
3,4,순위 동일,Deja Vu,RESCENE (리센느),Dearest,"58,937"
4,5,순위 동일,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,"66,158"
...,...,...,...,...,...,...
95,96,3단계 하락,Less than a Lover,제니 (JENNIE),Less than a Lover,"27,099"
96,97,15단계 하락,New York,임영웅,IM HERO 10,"24,268"
97,98,순위 동일,그댈 위한 멜로디,임영웅,IM HERO 2,"42,734"
98,99,1단계 상승,사랑은 봄비처럼...이별은 겨울비처럼...,임현정,All That Love,"76,461"
99,100,1단계 하락,REBEL HEART,IVE (아이브),IVE EMPATHY,"122,858"

In [ ]:
df_melon100.to_csv('../data/멜론Top100_251001.csv', encoding='utf-8')